### ISSUE TITLE
Course asset entries are not removed on course deletion

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-courseassets#3]
When a course is deleted the courseassets database collection retains the content-asset relationships.

When subsequently trying to remove an asset no longer in use the following error occurs:

![Image](https://github.com/adapt-security/adapt-authoring-courseassets/assets/1228225/82352f7d-1098-48e7-891f-8bdd9850bc26)

**Comment by joe-allen-89** [comment]
I'm able to replicate this issue, it's still present in the courseassets after the course has been deleted.

**Comment by taylortom** [comment]
Fixed

**Comment by joe-allen-89** [comment]
asset being removed from courseassets as expected.
